/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Button: typeof import('primereact/button')['Button']
  const Card: typeof import('primereact/card')['Card']
  const InputText: typeof import('primereact/inputText')['InputText']
  const Password: typeof import('primereact/password')['Password']
}
